apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: final-project
          image: registry.digitalocean.com/vttpb-final-project/reference95/final-project:v10
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: SPRING_DATA_MONGODB_URI
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPOONCULAR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: SPOONCULAR_API_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: STRIPE_SECRET_KEY
            - name: BREVO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: final-project-secret
                  key: BREVO_API_KEY

            - name: FRONTEND_BASE_URL
              value: "http://104.248.99.238"
            - name: BREVO_SENDER_EMAIL
              value: "calvinmj96@gmail.com"
            - name: BREVO_SENDER_NAME
              value: "Recipe Finder App"